export const DEFAULT_MEMBERSHIP_TIERS = [
  {
    name: "支持者",
    slug: "supporter",
    description: "支持创作者持续更新，并获得支持者身份与基础会员内容。",
    priceLabel: "¥9 / 月",
    priceAmountMinor: 900,
    currency: "cny",
    level: 10,
    durationDays: 31,
    sortOrder: 1,
  },
  {
    name: "高清图会员",
    slug: "hd-member",
    description: "查看高清原图与高分辨率会员内容。",
    priceLabel: "¥29 / 月",
    priceAmountMinor: 2900,
    currency: "cny",
    level: 20,
    durationDays: 31,
    sortOrder: 2,
  },
  {
    name: "素材包会员",
    slug: "pack-member",
    description: "解锁高清内容，并下载创作素材包与配套资源。",
    priceLabel: "¥59 / 月",
    priceAmountMinor: 5900,
    currency: "cny",
    level: 30,
    durationDays: 31,
    sortOrder: 3,
  },
];
